# Generated by Django 2.2.9 on 2020-01-13 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('product', models.UUIDField()),
                ('user', models.UUIDField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('payment_validation_requested', 'Pending Payment'), ('request_rejected', 'Order Rejected'), ('storage_approved', 'Approved by Storage'), ('delivery_requested', 'Delivery Requested'), ('failed', 'Order Failed')], max_length=100)),
            ],
            bases=('api.basemodel',),
        ),
    ]
