FROM python:3.6-slim

WORKDIR /products

COPY requirements.txt /products
RUN pip install -r requirements.txt

COPY . /products

EXPOSE 8000

RUN chmod +x deploy/docker-django.sh
ENTRYPOINT ["bash", "docker-django.sh"]
