# Generated by Django 2.2.9 on 2020-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageoperation',
            name='order',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storageoperation',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='requested', max_length=100),
        ),
    ]
