FROM python:3.6-slim

WORKDIR /storage

COPY requirements.txt /storage
RUN pip install -r requirements.txt

COPY . /storage

EXPOSE 8000

RUN chmod +x deploy/docker-django.sh
ENTRYPOINT ["bash", "docker-django.sh"]
