
FROM python:3.6-slim

# This dockerfile could be unique to multiple services in services folder.

WORKDIR /service

COPY requirements.txt /service
RUN pip install -r requirements.txt

COPY . /service

RUN chmod +x docker-service.sh
ENTRYPOINT ["bash", "docker-service.sh"]
