# Generated by Django 2.2.9 on 2020-01-13 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseModel')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProductType')),
            ],
            bases=('api.basemodel',),
        ),
    ]
