FROM python:3.6-slim

WORKDIR /orders

COPY requirements.txt /orders
RUN pip install -r requirements.txt

COPY . /orders

EXPOSE 8000

RUN chmod +x deploy/docker-django.sh
ENTRYPOINT ["bash", "docker-django.sh"]
