AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

max_workers: ${MAX_WORKERS:3}
parent_calls_tracked: 10

LOGGING:
    version: 1
    disable_existing_loggers: False
    formatters:
        standard:
            format: '[%(asctime)s] %(threadName)s, %(name)s, %(levelname)s [%(filename)s:%(lineno)d]:  %(message)s'
            datefmt: '%d/%m/%Y %H:%M:%S'
        djangolog:
            format: '[%(asctime)s] - %(name)s, [%(filename)s:%(lineno)d]: %(message)s'
            datefmt: '%d/%m/%Y %H:%M:%S'
    handlers:
        service:
            level: ${LOG_LEVEL:INFO}
            class: logging.handlers.RotatingFileHandler
            filename: log/service.log
            maxBytes: 2097152
            backupCount: 10
            formatter: djangolog
        console:
            level: ${LOG_LEVEL:INFO}
            class: logging.StreamHandler
            formatter: standard
    loggers:
        service:
            handlers: [console, service]
            propagate: True
            level: ${LOG_LEVEL:INFO}

